// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.12.4
// source: app/grpc/shortener.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SimpleShortRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Url string `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
}

func (x *SimpleShortRequest) Reset() {
	*x = SimpleShortRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_app_grpc_shortener_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SimpleShortRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SimpleShortRequest) ProtoMessage() {}

func (x *SimpleShortRequest) ProtoReflect() protoreflect.Message {
	mi := &file_app_grpc_shortener_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SimpleShortRequest.ProtoReflect.Descriptor instead.
func (*SimpleShortRequest) Descriptor() ([]byte, []int) {
	return file_app_grpc_shortener_proto_rawDescGZIP(), []int{0}
}

func (x *SimpleShortRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type SimpleShortResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Short string `protobuf:"bytes,1,opt,name=short,proto3" json:"short,omitempty"`
}

func (x *SimpleShortResponse) Reset() {
	*x = SimpleShortResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_app_grpc_shortener_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SimpleShortResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SimpleShortResponse) ProtoMessage() {}

func (x *SimpleShortResponse) ProtoReflect() protoreflect.Message {
	mi := &file_app_grpc_shortener_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SimpleShortResponse.ProtoReflect.Descriptor instead.
func (*SimpleShortResponse) Descriptor() ([]byte, []int) {
	return file_app_grpc_shortener_proto_rawDescGZIP(), []int{1}
}

func (x *SimpleShortResponse) GetShort() string {
	if x != nil {
		return x.Short
	}
	return ""
}

type SimpleUnshortRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Short string `protobuf:"bytes,1,opt,name=short,proto3" json:"short,omitempty"`
}

func (x *SimpleUnshortRequest) Reset() {
	*x = SimpleUnshortRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_app_grpc_shortener_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SimpleUnshortRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SimpleUnshortRequest) ProtoMessage() {}

func (x *SimpleUnshortRequest) ProtoReflect() protoreflect.Message {
	mi := &file_app_grpc_shortener_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SimpleUnshortRequest.ProtoReflect.Descriptor instead.
func (*SimpleUnshortRequest) Descriptor() ([]byte, []int) {
	return file_app_grpc_shortener_proto_rawDescGZIP(), []int{2}
}

func (x *SimpleUnshortRequest) GetShort() string {
	if x != nil {
		return x.Short
	}
	return ""
}

type SimpleUnshortResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Url string `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
}

func (x *SimpleUnshortResponse) Reset() {
	*x = SimpleUnshortResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_app_grpc_shortener_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SimpleUnshortResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SimpleUnshortResponse) ProtoMessage() {}

func (x *SimpleUnshortResponse) ProtoReflect() protoreflect.Message {
	mi := &file_app_grpc_shortener_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SimpleUnshortResponse.ProtoReflect.Descriptor instead.
func (*SimpleUnshortResponse) Descriptor() ([]byte, []int) {
	return file_app_grpc_shortener_proto_rawDescGZIP(), []int{3}
}

func (x *SimpleUnshortResponse) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type PingRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *PingRequest) Reset() {
	*x = PingRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_app_grpc_shortener_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingRequest) ProtoMessage() {}

func (x *PingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_app_grpc_shortener_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingRequest.ProtoReflect.Descriptor instead.
func (*PingRequest) Descriptor() ([]byte, []int) {
	return file_app_grpc_shortener_proto_rawDescGZIP(), []int{4}
}

type PingResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *PingResponse) Reset() {
	*x = PingResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_app_grpc_shortener_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingResponse) ProtoMessage() {}

func (x *PingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_app_grpc_shortener_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingResponse.ProtoReflect.Descriptor instead.
func (*PingResponse) Descriptor() ([]byte, []int) {
	return file_app_grpc_shortener_proto_rawDescGZIP(), []int{5}
}

type APIUserURLRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *APIUserURLRequest) Reset() {
	*x = APIUserURLRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_app_grpc_shortener_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *APIUserURLRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*APIUserURLRequest) ProtoMessage() {}

func (x *APIUserURLRequest) ProtoReflect() protoreflect.Message {
	mi := &file_app_grpc_shortener_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use APIUserURLRequest.ProtoReflect.Descriptor instead.
func (*APIUserURLRequest) Descriptor() ([]byte, []int) {
	return file_app_grpc_shortener_proto_rawDescGZIP(), []int{6}
}

type APIUserURLResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Urls string `protobuf:"bytes,1,opt,name=urls,proto3" json:"urls,omitempty"`
}

func (x *APIUserURLResponse) Reset() {
	*x = APIUserURLResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_app_grpc_shortener_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *APIUserURLResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*APIUserURLResponse) ProtoMessage() {}

func (x *APIUserURLResponse) ProtoReflect() protoreflect.Message {
	mi := &file_app_grpc_shortener_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use APIUserURLResponse.ProtoReflect.Descriptor instead.
func (*APIUserURLResponse) Descriptor() ([]byte, []int) {
	return file_app_grpc_shortener_proto_rawDescGZIP(), []int{7}
}

func (x *APIUserURLResponse) GetUrls() string {
	if x != nil {
		return x.Urls
	}
	return ""
}

type APIStatsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *APIStatsRequest) Reset() {
	*x = APIStatsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_app_grpc_shortener_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *APIStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*APIStatsRequest) ProtoMessage() {}

func (x *APIStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_app_grpc_shortener_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use APIStatsRequest.ProtoReflect.Descriptor instead.
func (*APIStatsRequest) Descriptor() ([]byte, []int) {
	return file_app_grpc_shortener_proto_rawDescGZIP(), []int{8}
}

type APIStatsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Stats string `protobuf:"bytes,1,opt,name=stats,proto3" json:"stats,omitempty"`
}

func (x *APIStatsResponse) Reset() {
	*x = APIStatsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_app_grpc_shortener_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *APIStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*APIStatsResponse) ProtoMessage() {}

func (x *APIStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_app_grpc_shortener_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use APIStatsResponse.ProtoReflect.Descriptor instead.
func (*APIStatsResponse) Descriptor() ([]byte, []int) {
	return file_app_grpc_shortener_proto_rawDescGZIP(), []int{9}
}

func (x *APIStatsResponse) GetStats() string {
	if x != nil {
		return x.Stats
	}
	return ""
}

type APIShortRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Jsonurl string `protobuf:"bytes,1,opt,name=jsonurl,proto3" json:"jsonurl,omitempty"`
}

func (x *APIShortRequest) Reset() {
	*x = APIShortRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_app_grpc_shortener_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *APIShortRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*APIShortRequest) ProtoMessage() {}

func (x *APIShortRequest) ProtoReflect() protoreflect.Message {
	mi := &file_app_grpc_shortener_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use APIShortRequest.ProtoReflect.Descriptor instead.
func (*APIShortRequest) Descriptor() ([]byte, []int) {
	return file_app_grpc_shortener_proto_rawDescGZIP(), []int{10}
}

func (x *APIShortRequest) GetJsonurl() string {
	if x != nil {
		return x.Jsonurl
	}
	return ""
}

type APIShortResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Jsonshort string `protobuf:"bytes,1,opt,name=jsonshort,proto3" json:"jsonshort,omitempty"`
}

func (x *APIShortResponse) Reset() {
	*x = APIShortResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_app_grpc_shortener_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *APIShortResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*APIShortResponse) ProtoMessage() {}

func (x *APIShortResponse) ProtoReflect() protoreflect.Message {
	mi := &file_app_grpc_shortener_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use APIShortResponse.ProtoReflect.Descriptor instead.
func (*APIShortResponse) Descriptor() ([]byte, []int) {
	return file_app_grpc_shortener_proto_rawDescGZIP(), []int{11}
}

func (x *APIShortResponse) GetJsonshort() string {
	if x != nil {
		return x.Jsonshort
	}
	return ""
}

type APIBatchShortRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Jsonurls string `protobuf:"bytes,1,opt,name=jsonurls,proto3" json:"jsonurls,omitempty"`
}

func (x *APIBatchShortRequest) Reset() {
	*x = APIBatchShortRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_app_grpc_shortener_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *APIBatchShortRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*APIBatchShortRequest) ProtoMessage() {}

func (x *APIBatchShortRequest) ProtoReflect() protoreflect.Message {
	mi := &file_app_grpc_shortener_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use APIBatchShortRequest.ProtoReflect.Descriptor instead.
func (*APIBatchShortRequest) Descriptor() ([]byte, []int) {
	return file_app_grpc_shortener_proto_rawDescGZIP(), []int{12}
}

func (x *APIBatchShortRequest) GetJsonurls() string {
	if x != nil {
		return x.Jsonurls
	}
	return ""
}

type APIBatchShortResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Jsonshorts string `protobuf:"bytes,1,opt,name=jsonshorts,proto3" json:"jsonshorts,omitempty"`
}

func (x *APIBatchShortResponse) Reset() {
	*x = APIBatchShortResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_app_grpc_shortener_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *APIBatchShortResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*APIBatchShortResponse) ProtoMessage() {}

func (x *APIBatchShortResponse) ProtoReflect() protoreflect.Message {
	mi := &file_app_grpc_shortener_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use APIBatchShortResponse.ProtoReflect.Descriptor instead.
func (*APIBatchShortResponse) Descriptor() ([]byte, []int) {
	return file_app_grpc_shortener_proto_rawDescGZIP(), []int{13}
}

func (x *APIBatchShortResponse) GetJsonshorts() string {
	if x != nil {
		return x.Jsonshorts
	}
	return ""
}

type APIUserShortDeleteRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Urls string `protobuf:"bytes,1,opt,name=urls,proto3" json:"urls,omitempty"`
}

func (x *APIUserShortDeleteRequest) Reset() {
	*x = APIUserShortDeleteRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_app_grpc_shortener_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *APIUserShortDeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*APIUserShortDeleteRequest) ProtoMessage() {}

func (x *APIUserShortDeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_app_grpc_shortener_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use APIUserShortDeleteRequest.ProtoReflect.Descriptor instead.
func (*APIUserShortDeleteRequest) Descriptor() ([]byte, []int) {
	return file_app_grpc_shortener_proto_rawDescGZIP(), []int{14}
}

func (x *APIUserShortDeleteRequest) GetUrls() string {
	if x != nil {
		return x.Urls
	}
	return ""
}

type APIUserShortDeleteResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *APIUserShortDeleteResponse) Reset() {
	*x = APIUserShortDeleteResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_app_grpc_shortener_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *APIUserShortDeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*APIUserShortDeleteResponse) ProtoMessage() {}

func (x *APIUserShortDeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_app_grpc_shortener_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use APIUserShortDeleteResponse.ProtoReflect.Descriptor instead.
func (*APIUserShortDeleteResponse) Descriptor() ([]byte, []int) {
	return file_app_grpc_shortener_proto_rawDescGZIP(), []int{15}
}

var File_app_grpc_shortener_proto protoreflect.FileDescriptor

var file_app_grpc_shortener_proto_rawDesc = []byte{
	0x0a, 0x18, 0x61, 0x70, 0x70, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x73, 0x68, 0x6f, 0x72, 0x74,
	0x65, 0x6e, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x67, 0x72, 0x70, 0x63,
	0x22, 0x26, 0x0a, 0x12, 0x53, 0x69, 0x6d, 0x70, 0x6c, 0x65, 0x53, 0x68, 0x6f, 0x72, 0x74, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x72, 0x6c, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x72, 0x6c, 0x22, 0x2b, 0x0a, 0x13, 0x53, 0x69, 0x6d, 0x70,
	0x6c, 0x65, 0x53, 0x68, 0x6f, 0x72, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x14, 0x0a, 0x05, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x73, 0x68, 0x6f, 0x72, 0x74, 0x22, 0x2c, 0x0a, 0x14, 0x53, 0x69, 0x6d, 0x70, 0x6c, 0x65, 0x55,
	0x6e, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a,
	0x05, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x73, 0x68,
	0x6f, 0x72, 0x74, 0x22, 0x29, 0x0a, 0x15, 0x53, 0x69, 0x6d, 0x70, 0x6c, 0x65, 0x55, 0x6e, 0x73,
	0x68, 0x6f, 0x72, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x10, 0x0a, 0x03,
	0x75, 0x72, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x72, 0x6c, 0x22, 0x0d,
	0x0a, 0x0b, 0x50, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x0e, 0x0a,
	0x0c, 0x50, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x13, 0x0a,
	0x11, 0x41, 0x50, 0x49, 0x55, 0x73, 0x65, 0x72, 0x55, 0x52, 0x4c, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x22, 0x28, 0x0a, 0x12, 0x41, 0x50, 0x49, 0x55, 0x73, 0x65, 0x72, 0x55, 0x52, 0x4c,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x75, 0x72, 0x6c, 0x73,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x75, 0x72, 0x6c, 0x73, 0x22, 0x11, 0x0a, 0x0f,
	0x41, 0x50, 0x49, 0x53, 0x74, 0x61, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22,
	0x28, 0x0a, 0x10, 0x41, 0x50, 0x49, 0x53, 0x74, 0x61, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x74, 0x73, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x73, 0x74, 0x61, 0x74, 0x73, 0x22, 0x2b, 0x0a, 0x0f, 0x41, 0x50, 0x49,
	0x53, 0x68, 0x6f, 0x72, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07,
	0x6a, 0x73, 0x6f, 0x6e, 0x75, 0x72, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6a,
	0x73, 0x6f, 0x6e, 0x75, 0x72, 0x6c, 0x22, 0x30, 0x0a, 0x10, 0x41, 0x50, 0x49, 0x53, 0x68, 0x6f,
	0x72, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x6a, 0x73,
	0x6f, 0x6e, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x6a,
	0x73, 0x6f, 0x6e, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x22, 0x32, 0x0a, 0x14, 0x41, 0x50, 0x49, 0x42,
	0x61, 0x74, 0x63, 0x68, 0x53, 0x68, 0x6f, 0x72, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x1a, 0x0a, 0x08, 0x6a, 0x73, 0x6f, 0x6e, 0x75, 0x72, 0x6c, 0x73, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x6a, 0x73, 0x6f, 0x6e, 0x75, 0x72, 0x6c, 0x73, 0x22, 0x37, 0x0a, 0x15,
	0x41, 0x50, 0x49, 0x42, 0x61, 0x74, 0x63, 0x68, 0x53, 0x68, 0x6f, 0x72, 0x74, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x6a, 0x73, 0x6f, 0x6e, 0x73, 0x68, 0x6f,
	0x72, 0x74, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x6a, 0x73, 0x6f, 0x6e, 0x73,
	0x68, 0x6f, 0x72, 0x74, 0x73, 0x22, 0x2f, 0x0a, 0x19, 0x41, 0x50, 0x49, 0x55, 0x73, 0x65, 0x72,
	0x53, 0x68, 0x6f, 0x72, 0x74, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x75, 0x72, 0x6c, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x75, 0x72, 0x6c, 0x73, 0x22, 0x1c, 0x0a, 0x1a, 0x41, 0x50, 0x49, 0x55, 0x73, 0x65,
	0x72, 0x53, 0x68, 0x6f, 0x72, 0x74, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x32, 0xa3, 0x04, 0x0a, 0x09, 0x53, 0x68, 0x6f, 0x72, 0x74, 0x65, 0x6e,
	0x65, 0x72, 0x12, 0x42, 0x0a, 0x0b, 0x53, 0x69, 0x6d, 0x70, 0x6c, 0x65, 0x53, 0x68, 0x6f, 0x72,
	0x74, 0x12, 0x18, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x53, 0x69, 0x6d, 0x70, 0x6c, 0x65, 0x53,
	0x68, 0x6f, 0x72, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e, 0x67, 0x72,
	0x70, 0x63, 0x2e, 0x53, 0x69, 0x6d, 0x70, 0x6c, 0x65, 0x53, 0x68, 0x6f, 0x72, 0x74, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x48, 0x0a, 0x0d, 0x53, 0x69, 0x6d, 0x70, 0x6c, 0x65,
	0x55, 0x6e, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x12, 0x1a, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x53,
	0x69, 0x6d, 0x70, 0x6c, 0x65, 0x55, 0x6e, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x1b, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x53, 0x69, 0x6d, 0x70, 0x6c,
	0x65, 0x55, 0x6e, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x2d, 0x0a, 0x04, 0x50, 0x69, 0x6e, 0x67, 0x12, 0x11, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e,
	0x50, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x12, 0x2e, 0x67, 0x72,
	0x70, 0x63, 0x2e, 0x50, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x40, 0x0a, 0x0b, 0x41, 0x50, 0x49, 0x55, 0x73, 0x65, 0x72, 0x55, 0x52, 0x4c, 0x73, 0x12, 0x17,
	0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x41, 0x50, 0x49, 0x55, 0x73, 0x65, 0x72, 0x55, 0x52, 0x4c,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x41,
	0x50, 0x49, 0x55, 0x73, 0x65, 0x72, 0x55, 0x52, 0x4c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x39, 0x0a, 0x08, 0x41, 0x50, 0x49, 0x53, 0x74, 0x61, 0x74, 0x73, 0x12, 0x15, 0x2e,
	0x67, 0x72, 0x70, 0x63, 0x2e, 0x41, 0x50, 0x49, 0x53, 0x74, 0x61, 0x74, 0x73, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x41, 0x50, 0x49, 0x53,
	0x74, 0x61, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x39, 0x0a, 0x08,
	0x41, 0x50, 0x49, 0x53, 0x68, 0x6f, 0x72, 0x74, 0x12, 0x15, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e,
	0x41, 0x50, 0x49, 0x53, 0x68, 0x6f, 0x72, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x16, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x41, 0x50, 0x49, 0x53, 0x68, 0x6f, 0x72, 0x74, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x48, 0x0a, 0x0d, 0x41, 0x50, 0x49, 0x42, 0x61,
	0x74, 0x63, 0x68, 0x53, 0x68, 0x6f, 0x72, 0x74, 0x12, 0x1a, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e,
	0x41, 0x50, 0x49, 0x42, 0x61, 0x74, 0x63, 0x68, 0x53, 0x68, 0x6f, 0x72, 0x74, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x1b, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x41, 0x50, 0x49, 0x42,
	0x61, 0x74, 0x63, 0x68, 0x53, 0x68, 0x6f, 0x72, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x57, 0x0a, 0x12, 0x41, 0x50, 0x49, 0x55, 0x73, 0x65, 0x72, 0x53, 0x68, 0x6f, 0x72,
	0x74, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x12, 0x1f, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x41,
	0x50, 0x49, 0x55, 0x73, 0x65, 0x72, 0x53, 0x68, 0x6f, 0x72, 0x74, 0x44, 0x65, 0x6c, 0x65, 0x74,
	0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x20, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e,
	0x41, 0x50, 0x49, 0x55, 0x73, 0x65, 0x72, 0x53, 0x68, 0x6f, 0x72, 0x74, 0x44, 0x65, 0x6c, 0x65,
	0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x0c, 0x5a, 0x0a, 0x67, 0x72,
	0x70, 0x63, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_app_grpc_shortener_proto_rawDescOnce sync.Once
	file_app_grpc_shortener_proto_rawDescData = file_app_grpc_shortener_proto_rawDesc
)

func file_app_grpc_shortener_proto_rawDescGZIP() []byte {
	file_app_grpc_shortener_proto_rawDescOnce.Do(func() {
		file_app_grpc_shortener_proto_rawDescData = protoimpl.X.CompressGZIP(file_app_grpc_shortener_proto_rawDescData)
	})
	return file_app_grpc_shortener_proto_rawDescData
}

var file_app_grpc_shortener_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_app_grpc_shortener_proto_goTypes = []interface{}{
	(*SimpleShortRequest)(nil),         // 0: grpc.SimpleShortRequest
	(*SimpleShortResponse)(nil),        // 1: grpc.SimpleShortResponse
	(*SimpleUnshortRequest)(nil),       // 2: grpc.SimpleUnshortRequest
	(*SimpleUnshortResponse)(nil),      // 3: grpc.SimpleUnshortResponse
	(*PingRequest)(nil),                // 4: grpc.PingRequest
	(*PingResponse)(nil),               // 5: grpc.PingResponse
	(*APIUserURLRequest)(nil),          // 6: grpc.APIUserURLRequest
	(*APIUserURLResponse)(nil),         // 7: grpc.APIUserURLResponse
	(*APIStatsRequest)(nil),            // 8: grpc.APIStatsRequest
	(*APIStatsResponse)(nil),           // 9: grpc.APIStatsResponse
	(*APIShortRequest)(nil),            // 10: grpc.APIShortRequest
	(*APIShortResponse)(nil),           // 11: grpc.APIShortResponse
	(*APIBatchShortRequest)(nil),       // 12: grpc.APIBatchShortRequest
	(*APIBatchShortResponse)(nil),      // 13: grpc.APIBatchShortResponse
	(*APIUserShortDeleteRequest)(nil),  // 14: grpc.APIUserShortDeleteRequest
	(*APIUserShortDeleteResponse)(nil), // 15: grpc.APIUserShortDeleteResponse
}
var file_app_grpc_shortener_proto_depIdxs = []int32{
	0,  // 0: grpc.Shortener.SimpleShort:input_type -> grpc.SimpleShortRequest
	2,  // 1: grpc.Shortener.SimpleUnshort:input_type -> grpc.SimpleUnshortRequest
	4,  // 2: grpc.Shortener.Ping:input_type -> grpc.PingRequest
	6,  // 3: grpc.Shortener.APIUserURLs:input_type -> grpc.APIUserURLRequest
	8,  // 4: grpc.Shortener.APIStats:input_type -> grpc.APIStatsRequest
	10, // 5: grpc.Shortener.APIShort:input_type -> grpc.APIShortRequest
	12, // 6: grpc.Shortener.APIBatchShort:input_type -> grpc.APIBatchShortRequest
	14, // 7: grpc.Shortener.APIUserShortDelete:input_type -> grpc.APIUserShortDeleteRequest
	1,  // 8: grpc.Shortener.SimpleShort:output_type -> grpc.SimpleShortResponse
	3,  // 9: grpc.Shortener.SimpleUnshort:output_type -> grpc.SimpleUnshortResponse
	5,  // 10: grpc.Shortener.Ping:output_type -> grpc.PingResponse
	7,  // 11: grpc.Shortener.APIUserURLs:output_type -> grpc.APIUserURLResponse
	9,  // 12: grpc.Shortener.APIStats:output_type -> grpc.APIStatsResponse
	11, // 13: grpc.Shortener.APIShort:output_type -> grpc.APIShortResponse
	13, // 14: grpc.Shortener.APIBatchShort:output_type -> grpc.APIBatchShortResponse
	15, // 15: grpc.Shortener.APIUserShortDelete:output_type -> grpc.APIUserShortDeleteResponse
	8,  // [8:16] is the sub-list for method output_type
	0,  // [0:8] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_app_grpc_shortener_proto_init() }
func file_app_grpc_shortener_proto_init() {
	if File_app_grpc_shortener_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_app_grpc_shortener_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SimpleShortRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_app_grpc_shortener_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SimpleShortResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_app_grpc_shortener_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SimpleUnshortRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_app_grpc_shortener_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SimpleUnshortResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_app_grpc_shortener_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PingRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_app_grpc_shortener_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PingResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_app_grpc_shortener_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*APIUserURLRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_app_grpc_shortener_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*APIUserURLResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_app_grpc_shortener_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*APIStatsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_app_grpc_shortener_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*APIStatsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_app_grpc_shortener_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*APIShortRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_app_grpc_shortener_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*APIShortResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_app_grpc_shortener_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*APIBatchShortRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_app_grpc_shortener_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*APIBatchShortResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_app_grpc_shortener_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*APIUserShortDeleteRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_app_grpc_shortener_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*APIUserShortDeleteResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_app_grpc_shortener_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_app_grpc_shortener_proto_goTypes,
		DependencyIndexes: file_app_grpc_shortener_proto_depIdxs,
		MessageInfos:      file_app_grpc_shortener_proto_msgTypes,
	}.Build()
	File_app_grpc_shortener_proto = out.File
	file_app_grpc_shortener_proto_rawDesc = nil
	file_app_grpc_shortener_proto_goTypes = nil
	file_app_grpc_shortener_proto_depIdxs = nil
}
